config/routes.rb
Upnews::Application.routes.draw do

  devise_for :admins
  devise_for :editors

  resources :articles
  resources :infografics
  resources :pdfpages
  resources :reclams  

  get "mainpage/index" 
  

  root :to => 'mainpage#index', :as => 'mainpage'

  match '/articles' => 'articles#index'

  match '/pdfpages' => 'pdfpages#index'

  match '/uppdf1' => 'pdfpages#uppdf', as: 'uppdf'
  match '/vppdf' => 'pdfpages#vppdf', as: 'vppdf'
  match '/tdpdf' => 'pdfpages#tdpdf', as: 'tdpdf'

  match '/reclams' => 'reclams#index'

  match '/infografics' => 'infografics#index'  

  match '/articles_search' => 'articles#search',  as: 'search'  

  match '/devise' => 'devise#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/article.rb
# -*- encoding : utf-8 -*-

require 'image_clearer'

class Article < ActiveRecord::Base
  include ImageClearer
  attr_accessible :anonce, :author, :content, :edition, :id, :pdf_file, :priority, :pub_time, :rubric, :title, :undertitle, :genre, :image

  has_attached_file :image,
      :path => ":rails_root/public/assets/:class/:id/:style/:filename",
      :url => "/assets/:class/:id/:style/:filename"
      # з’ясувати, який шлях потрібен? :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      #:url => "/system/attachment/:id/:style/:filename"

  clear_image_for :image
  
  searchable do
    text :title, :boost => 5.0 
    text :anonce, :content 
  end
  
end

app/controllers/articles_controller.rb
# -*- encoding : utf-8 -*-
class ArticlesController < ApplicationController
  
  #before_filter :authenticate, :except => [:index, :search, :show]

  # GET /articles
  # GET /articles.json
 def index
   @articles = Article.order(sort_column + ' ' + sort_direction).paginate page: params[:page], per_page: 200
   @sort_column = sort_column
   @sort_direction = sort_direction
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles
  # GET /articles.json
  def search
    @search = Article.search do
      fulltext params[:search]
    end
    @results_number = @search.results.size
    @articles = @search.results.last(200).paginate(page: params[:page], per_page:100)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Статья была успешна создана (Article was successfully created).' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new", layout: "articles" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Изменения в статью внесены успешно (Article was successfully updated).' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "articles" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  #def authenticate
    #authenticate_or_request_with_http_basic do |username, password|
    #  username == "admins" && password == "seenmnb"
    # end
  #end

  private
    def sort_column
      Article.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end
  
    def sort_direction
      %w[ASC DESC].include?(params[:direction]) ?  params[:direction] : "ASC"
    end  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
  <div>
  <%= form_for(@article, html: { multipart: true}) do |f| %> 
  <%# form_for(@article, url: articles_path, html: { multipart: true}) do |f| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %> <!-- do -->
        </ul>

      </div> <!-- error explanation -->
    <% end %>  <!-- if -->

  <p>Звездочкой (*) помечены обязательные для ввода поля</p> 
  <div class="field" id="inp_genre">
    <%= f.label "*вид статьи" %>
    <%= select(:article,:genre, options_for_select([['статья', 'статья'], ['новость', 'новость'], ['тема дня', 'тема дня'], ['топ', 'топ']], @article.genre || 'новость')) %>
  </div>

  <div class="field" id="inp_rubric">
    <%= f.label "*рубрика" %>
    <%= select(:article, :rubric, options_for_select([['Политика', 'Политика'], ['Власть', 'Власть'], ['Экономика', 'Экономика'], ['Социум', 'Социум'], ['Культура', 'Культура'], ['Человек', 'Человек'], ['Мир', 'Мир'], ['Украина', 'Украина'], ['Николаевщина', 'Николаевщина']], @article.rubric || 'Политика')) %>
  </div>

  <div class="field" id="inp_zag">
    <%= f.label "*заголовок" %>
    <%= f.text_field :title, required: "true", size: 62 %>
  </div>

  <div class="field" id="inp_text">
    <%= f.label "*текст статьи" %><br />
    <%= f.text_area :content, required: "true", rows: 7, cols: 125 %>
  </div>

  <div class="field">
    <%= f.label "анонс" %>
    <%= f.text_field :anonce, size: 88  %>
  </div>

      <!--<div class="field" id="inp_created">
        <%# f.label "* дата создания" %><br />
        <%# f.datetime :created_at, required: "true" %>
      </div>

      <div class="field" id="inp_updated">
        <%# f.label "* дата посл. изменения" %><br />
        <%# f.datetime :updated_at, required: "true" %>
      </div> -->

      <%# <div class="field" id="inp_pubtime"%>
      <%# f.label "* опубликовать [DD-MM-YYYY HH:MM]"  %>
      <%# t=Time.now %>
      <%# f.number_field :pub_time,  placeholder: t.strftime("%d-%m-%Y %H:%M"), required: "true" %> 
      <%#/div %>

      <div class="field" id="inp_author">
        <%= f.label "* автор" %>
        <%= f.text_field :author, required: "true" %>
      </div>

      <div class="field" id="inp_edition">
        <%= f.label "издание" %>
        <%= f.text_field :edition %>
      </div>

      <div class="field" id="inp_image">
        <%= f.label "картинка" %>
        <%= f.file_field :image %>
        <% if @article.image? %>
          <%= image_tag(@article.image.url, size: "200x120") %> <br />
          <%= @article.image_file_name  %>
        <% end %>
      </div>

      <div class="actions">
        <%= f.submit  "Сохранить" %>
      </div>
    <% end %>
</div>

app/views/articles/edit.html.erb
<div class = "editor">
<% if editor_signed_in? %>
	<h4>Редактирование СТАТЬИ (НОВОСТИ)</h4>
	<%= render 'form' %>

	<div style="clear:both;">
		<%= link_to 'Показать', @article %> |
		<%= link_to 'Список', articles_path %>
	</div>
<% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %>	
</div>

app/views/articles/index.html.erb
 <div class = "editor">

<% if editor_signed_in? %>
    <div> <h4>Перечень СТАТЕЙ <%#= __Редактор:  current_editor.email %>   </h4> </div>

    <nav class="action">
        <%= link_to 'ДОБАВИТЬ СТАТЬЮ', new_article_path %>
    </nav>

    <div class = "digg_pagination"><%= will_paginate @articles %></div>
    </br>
    <table class = "artys">
        <tr class = "tablehead">
            <!-- background-color : #555;-->
            <th style = "width:13em;"><%= sortable "created_at", "Дата" %></th>
            <th style = "width:12em;"><%= sortable "rubric", "Рубрика" %></th>
            <th style = "width:8em;"><%= sortable "genre", "Жанр" %></th>
            <th style = "width:19em;"><%= sortable "author", "Автор" %></th>
            <th style = "width:28em;">Заголовок</th>
            <th style = "width:8em;">Фото</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
      <% @articles.each do |article| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td ><%= article.created_at.getlocal.strftime("%m/%d/%y %H:%M ") %></td>
            <td><%= truncate(strip_tags(article.rubric), length: 12) %></td>
            <td><%= truncate(strip_tags(article.genre),  length: 10) %></td>
            <td><%= truncate(strip_tags(article.author), length: 15) %></td>
            <td><%= truncate(strip_tags(article.title),  length: 28) %></td>
            <td><%= truncate(strip_tags(article.image_file_name),  length: 8) %></td>
            <td class="list_actions"><%= link_to 'Просмотр', article %></td>
            <td class="list_actions"><%= link_to 'Изменить', edit_article_path(article) %></td>
            <td class="list_actions"><%= link_to 'Удалить', article, confirm: 'Уверены?', method: :delete %></td>
        </tr>
      <% end %>
    </table>

    <br />

    <div class = "digg_pagination"><%= will_paginate @articles %></div>

<% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %> 

</div>

app/views/articles/new.html.erb
<div class= "editor">
	<% if editor_signed_in? %>
		<%= render 'form' %>
		<div id="back_button">
			<%= link_to 'Список', articles_path %>
		</div>
	<% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
	<% end %>
</div>

app/views/articles/news_item.html.erb
<p id="notice"><%= notice %></p>

<hgroup>
  <header class="rubric" >
    <%= @article.rubric %>
  </header>

  <header class="title">
    <%= @article.title %>
  </header>
</hgroup>

<p>
  <%= @article.undertitle %>
</p>
<p>
  <%= @article.pub_time %>
</p>
<br>
<div class="text">
   <%= @article.content %>
</div>
<div class="author">
  <b>автор: <%= @article.author %></b>
</div>
<div class="edition"> 
  <b>издание: <%= @article.edition %></b>
</div>

<div>
  ШШШШШШШШШШШ Другие материалы этой рубрики: ШШШШШШШШШШ
</div>

app/views/articles/search.html.erb
<div class="editor">
<!-- div style = "padding: 0xp 30px 0px 30px;" -->    
    <h3> НАЙДЕНО СТАТЕЙ: <%= @results_number %> </h3>
    <div class = "digg_pagination"><%= will_paginate @articles %>
    </div>
    <% @articles.each do |article| %>
      <section class="article_list">
        <div class = "ntime" style = "display: inline; margin:0px;">
            <% ndate = article.updated_at %>
            <%= ndate.strftime("%Y %d/%m  %H:%M") %> .......
            <b>рубрика:    </b><%= article.rubric %> .......  
            <b>автор:      </b><%= article.author %> .......
            <b>издание:    </b><%= article.edition %> ......
            <b>ID:         </b><%= article.id %></p>
        </div>
        <div class="zag" style="font-weight: bold;">   
            <%= link_to article.title, 
                controller: "mainpage",
                action: "show_item",
                id: article.id,
                style: "font-size:18px;" %>
        </div>    
        <p class="anonce" style="margin:0px;"> <%= sanitize(article.anonce) %> </p>
        <p  style="margin:0px;">-----------------------------------------------------------------------</p>
      </section>
    <% end %>
    <br />
    <div class = "digg_pagination"><%= will_paginate @articles %>
    </div>
<!-- /div -->      
</div>

app/views/articles/show.html.erb
<div class = "editor">
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>

<div style= "float:left; width:460px;">
	<p> <b>Id:</b> <%= @article.id %> </p>
	<p> <b>создано: </b><%= @article.created_at.strftime("%Y-%m-%d %H:%M") %> </p>
	<p> <b>изменено: </b> <%= @article.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
	<p> <b>рубрика:</b>  <%= @article.rubric %> </p>
	<p> <b>жанр:</b> <%= @article.genre %></p>
	<p> <b>автор:   </b> <%= @article.author %></p>
	<p>	<b>издание: </b><%= @article.edition %></p>
	<p> <b>анонс:   </b> <%= @article.anonce %></p>
</div>
<div style= "float:right; width:460px; ">	
	<h1><%= @article.title %></h1>
	<p> <%= sanitize(truncate(strip_tags(@article.content), length: 500)) %> </p>
	<!-- <p> <b>фото:    </b> <%= @article.image %> </p> -->
	<% if @article.image? %>
	  <%# image_tag @article.image_file_name, size: "200x120" %>
	  <%= image_tag(@article.image.url, size: "200x120") %>
	  <br />
	<%# link_to @article.image.url, @article.image.url  %>
	<%= @article.image_file_name + ",  размер:" + @article.image_file_size.to_s  %>
	<% end %>
</div>	
	<div style = "clear:both; float:right; padding-right:20px;">
	<%= link_to 'Редактировать', edit_article_path(@article) %> |
	<%= link_to 'Список', articles_path %>
	</div>
</div>