config/routes.rb
Upnews::Application.routes.draw do

  devise_for :admins
  devise_for :editors

  resources :articles
  resources :infografics
  resources :pdfpages
  resources :reclams  

  get "mainpage/index" 
  

  root :to => 'mainpage#index', :as => 'mainpage'

  match '/articles' => 'articles#index'

  match '/pdfpages' => 'pdfpages#index'

  match '/uppdf1' => 'pdfpages#uppdf', as: 'uppdf'
  match '/vppdf' => 'pdfpages#vppdf', as: 'vppdf'
  match '/tdpdf' => 'pdfpages#tdpdf', as: 'tdpdf'

  match '/reclams' => 'reclams#index'

  match '/infografics' => 'infografics#index'  

  match '/articles_search' => 'articles#search',  as: 'search'  

  match '/devise' => 'devise#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_footer.html.erb
<footer id="footer_block">
				<p>&copy КП НГПГ МО "Южная правда".&nbsp Все права зарезервированы.&nbsp При копировании материалов ссылка обязательна.</br>
				E-mail редакции: <a style= "color: #8FF; font-weight: bold;" href ="mailto:up@email.com.ua">up@email.com.ua</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
				Администратор сайта: <a style= "color: #8FF; font-weight: bold;" href="mailto: sergugol@gmail.com">sergugol@gmail.com</a></p>
</footer> <!-- end .footer -->

app/views/shared/_header.html.erb
<header id="header_block">
	<div id="date"> 
		<% t=Time.now.getlocal 
		weekday = ["воскресенье","понедельник","вторник","среда","четверг","пятница","суббота"] 
		@monthname = ["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"]	%>
		<p><%= weekday[t.wday] %> </p>
		<p><%= t.strftime("%d" + " " + @monthname[t.month - 1]) %> </p>
		<p><%= t.strftime("%Y" + " г.") %> </p>
	</div> 

	<div id="time"> 
			<p id="clock2">  </p>
	</div> 

	<div id="action_menu_bar1"> 
		<ul>
			<li><%= link_to 'Контакты',  action: "contacts" %></li>
			<li><%= link_to 'О газете',  action: "upnewsinfo" %></li>
			<li><%= link_to 'О рекламе', action: "reclaminfo" %></li>
			
		</ul>
	</div>

	<a id="tellnews" href="mailto: up@email.com.ua, rask2007@ukr.net"><u>Сообщить новость</u> </a>	

	<hgroup>
		<div id="logo"> 
			<%= link_to(image_tag("ngpgmoUP_logo_big_gray_566x100.png", :alt => "logo"), mainpage_path) %>
		</div>
	</hgroup>

	<div id="search_bar"> 	
		<%= form_tag search_path, :method => :get do %>
	  		<p>
	    	<%= text_field_tag :search, params[:search] %>
	    	<%= submit_tag "Поиск", :name => nil %>
		<% end %>
	</div>

	<div id="topic_band"><p> </p> </div>
	<nav id="topic_menu_bar"> 
		<ul>
			<li><%= link_to 'ГЛАВНАЯ', mainpage_path %></li>
							<!-- було "mainpage/index" і працювало з *other/mainpage/index  -->
							<!-- root_path   не працює, тому що root перевизначен як mainpage -->
			
			<li><%= link_to 'Мир', 
							controller: "mainpage",
							action: "worldnews_index" %></li>
			
			<li><%= link_to 'Украина', 
							controller: "mainpage",
							action: "ukrainenews_index" %></li>

			<li><%= link_to 'Николаев и обл.', 
							controller: "mainpage",
							action: "nikolaevnews_index" %></li>

			<li><%= link_to 'ПОЛИТИКА',
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Политика" %></li>

			<li><%= link_to 'ВЛАСТЬ', 
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Власть" %></li>

			<li><%= link_to 'ЭКОНОМИКА', 
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Экономика" %></li>	

			<li><%= link_to 'СОЦИУМ', 
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Социум" %></li>
			<li><%= link_to 'КУЛЬТУРА', 
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Культура" %></li>
			<li><%= link_to 'ЧЕЛОВЕК', 
							controller: "mainpage",
							action: "rubric_index",
							rubric_name: "Человек" %></li>

			<li><%= link_to 'Публикации', 
							controller: "mainpage",
							action: "allarticles_index" %></li>
		</ul>
	</nav>

	<div id="action_menu_bar2">
		<ul>
		<% if editor_signed_in? %>
			  	<li><%= link_to 'Статьи', controller: "articles" %></li>
				<li><%= link_to 'PDF', controller: "pdfpages" %></li>
				<li><%= link_to 'Инфограф.', controller: "infografics" %></li>
				<li><%= link_to 'Реклама', controller: "reclams" %></li>
				<li><%= link_to('Выход', destroy_editor_session_path, :method => :delete) %></li>
		<% else %>
			<li><%= link_to('Админ', new_editor_session_path)  %></li>
		<% end %> 
		</ul>
	</div>

</header> <!-- end .header -->