config/routes.rb
Upnews::Application.routes.draw do

  devise_for :admins
  devise_for :editors

  resources :articles
  resources :infografics
  resources :pdfpages
  resources :reclams  

  get "mainpage/index" 
  

  root :to => 'mainpage#index', :as => 'mainpage'

  match '/articles' => 'articles#index'

  match '/pdfpages' => 'pdfpages#index'

  match '/uppdf1' => 'pdfpages#uppdf', as: 'uppdf'
  match '/vppdf' => 'pdfpages#vppdf', as: 'vppdf'
  match '/tdpdf' => 'pdfpages#tdpdf', as: 'tdpdf'

  match '/reclams' => 'reclams#index'

  match '/infografics' => 'infografics#index'  

  match '/articles_search' => 'articles#search',  as: 'search'  

  match '/devise' => 'devise#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/pdfpage.rb
# -*- encoding : utf-8 -*-
class Pdfpage < ActiveRecord::Base
  attr_accessible :edition, :page_n, :image, :pdf_date, :pdf_n, :pdf_nn

	has_attached_file :image,
	  :path => ":rails_root/public/assets/:class/:attachment/:id_partition/:style/:filename",
                            :url => "/assets/:class/:attachment/:id_partition/:style/:filename"
	  #:path => ":rails_root/public/assets/:class/:attachment/:id/:style/:filename",
          #:url => "/system/:attachment/:id/:style/:filename"
end

app/controllers/pdfpages_controller.rb
# -*- encoding : utf-8 -*-
class PdfpagesController < ApplicationController

  # before_filter :authenticate

  # GET /pdfpages
  # GET /pdfpages.json
  def index
    @pdfpages = Pdfpage.order("edition").paginate page: params[:page], per_page: 20
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pdfpages }
    end
  end

  # GET /pdfpages
  # GET /pdfpages.json         .order("pdf_date")
  def uppdf
    @pdfpages = Pdfpage.find_all_by_edition("Южная правда").paginate page: params[:page], per_page: 20
    respond_to do |format|
      format.html # uppdf.html.erb
      format.json { render json: @pdfpages }
    end
  end

  # GET /pdfpages
  # GET /pdfpages.json
  def vppdf
    @pdfpages = Pdfpage.find_all_by_edition("Вестник Прибужья").paginate page: params[:page], per_page: 20
    respond_to do |format|
      format.html # vppdf.html.erb
      format.json { render json: @pdfpages }
    end
  end

    # GET /pdfpages
  # GET /pdfpages.json
  def tdpdf
    @pdfpages = Pdfpage.find_all_by_edition("Щотижня").paginate page: params[:page], per_page: 20
    respond_to do |format|
      format.html # tdpdf.html.erb
      format.json { render json: @pdfpages }
    end
  end

  # GET /pdfpages/1
  # GET /pdfpages/1.json
  def show
    @pdfpage = Pdfpage.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pdfpage }
    end
  end

  # GET /pdfpages/new
  # GET /pdfpages/new.json
  def new
    @pdfpage = Pdfpage.new

    @pdfpages_last = Pdfpage.order("created_at DESC").limit(20)
    #where('edition="Южная правда"').
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pdfpage }
    end
  end

  # GET /pdfpages/1/edit
  def edit
    @pdfpage = Pdfpage.find(params[:id])
    @pdfpages_last = Pdfpage.order("created_at DESC").limit(20)
    
  end

  # POST /pdfpages
  # POST /pdfpages.json
  def create
    @pdfpage = Pdfpage.new(params[:pdfpage])

    respond_to do |format|
      if @pdfpage.save
        format.html { redirect_to @pdfpage, notice: 'Pdfpage was successfully created.' }
        format.json { render json: @pdfpage, status: :created, location: @pdfpage }
      else
        format.html { render action: "new" }
        format.json { render json: @pdfpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pdfpages/1
  # PUT /pdfpages/1.json
  def update
    @pdfpage = Pdfpage.find(params[:id])

    respond_to do |format|
      if @pdfpage.update_attributes(params[:pdfpage])
        format.html { redirect_to @pdfpage, notice: 'Pdfpage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pdfpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfpages/1
  # DELETE /pdfpages/1.json
  def destroy
    @pdfpage = Pdfpage.find(params[:id])
    @pdfpage.destroy

    respond_to do |format|
      format.html { redirect_to pdfpages_url }
      format.json { head :no_content }
    end
  end
end

#============================ PDF-pages viewers ==========================================================


  # GET /pdfpages
  # GET /pdfpages.json
  def vppdf
    @pdfpages = Pdfpage.order("edition").paginate page: params[:page], per_page: 20

    respond_to do |format|
      format.html # uppdf.html.erb
      format.json { render json: @pdfpages }
    end
  end

  # GET /pdfpages
  # GET /pdfpages.json
  def tdpdf
    @pdfpages = Pdfpage.order("edition").paginate page: params[:page], per_page: 20

    respond_to do |format|
      format.html # uppdf.html.erb
      format.json { render json: @pdfpages }
    end
  end

app/helpers/pdfpages_helper.rb
module PdfpagesHelper
end

app/views/pdfpages/_form.html.erb
<div>
<%= form_for(@pdfpage, html: { multipart: true}) do |f| %>
  <% if @pdfpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pdfpage.errors.count, "error") %> prohibited this pdfpage from being saved:</h2>

      <ul>
      <% @pdfpage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h4>Редактирование PDF-файлов . . . . Редактор: <%# current_editor.email %> </h4>
  <div style = "float:left;">
    <h3>Последние добавленные:</h3>
    <% @pdfpages_last.each_with_index do |pdf, i| %>
        <%= sprintf('"%s" № %s ... %s с.  %s ',pdf.edition, pdf.pdf_n, pdf.page_n, pdf.image_file_name) %> <br /> 
    <% end %>
  </div>
  
<div style = "float:left; margin-left:20px;">
  <fieldset>   
        <div class="field">
          <%= f.label "Издание" %><br />
          <%= select(:pdfpage,:edition, options_for_select([['Южная правда', 'Южная правда'], ['Вестник Прибужья', 'Вестник Прибужья'], ['Щотижня', 'Щотижня']], @pdfpage.edition || 'Южная правда')) %>
        </div>
        
        <div class="field">
          <%= f.label "Дата выпуска" %><br />
          <%= f.date_select :pdf_date %>
        </div>
        
        <div class="field">
          <%= f.label "Номер выпуска ХХХ (внутри года)" %><br />
          <%= f.number_field :pdf_n %>
        </div>

        <div class="field">
          <%= f.label "Номер выпуска ХХХХХ (сквозной)" %><br />
          <%= f.number_field :pdf_nn, required: true %>
        </div>

        <div class="field">
          <%= f.label "Страница" %><br />
          <%= f.number_field :page_n, range:1..16 %>
        </div>
    
     
      <div class="field" id="inp_image" style="float: right;">
        <%= f.label "PDF-файл" %><br />
        <%= f.file_field :image %>
        <% if @pdfpage.image? %>
          <%= image_tag @pdfpage.image_file_name, :size => "60x90" %>
            <br />
            <%= @pdfpage.image_file_name  %>
        <% end %>
      </div>

      <div class="actions">
        <%= f.submit "Сохранить" %>
      </div>
   </fieldset>
</div>   
<% end %>
</div>

app/views/pdfpages/edit.html.erb
<div class = "editor">
  <% if editor_signed_in? %>
	<%= render 'form' %>

	<div style="clear:both;">
		<%= link_to 'Показать ', @pdfpage %> |
		<%= link_to 'Список', pdfpages_path %>
	</div>
  <% else %>
       <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
  <% end %>	
</div>

app/views/pdfpages/index.html.erb
<div class = "editor">

<% if editor_signed_in? %>
    <h4>Перечень PDF-ФАЙЛОВ </h4> <!--Редактор: --> <%#= current_editor.email %> 
    <nav class="action">
        <%= link_to 'ДОБАВИТЬ PDF-файл', new_pdfpage_path %>
    </nav>

    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
    <table style = "margin-left:auto; margin-right:auto;">
        <tr style = "padding:2px;">
            <th>Издание</th>
            <th>Дата выпуска</th>
            <th>NNN</th>
            <th>NNNNN</th>
            <th>№ стр.</th>
            <th>PDF-файл</th>
            <th>Розмер</th>
            <th>Дата_обновл.</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

       <% if @pdfpages.empty? %> 
        <div> PDF-файлы отсутствуют. </div>
        <% else %>         

             <% @pdfpages.each do |pdfpage| %>
             <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
                <td><%= pdfpage.edition %></td>
                <td><%= pdfpage.pdf_date %></td>
                <td><%= pdfpage.pdf_n %></td>
                <td><%= pdfpage.pdf_nn %></td>
                <td><%= pdfpage.page_n %></td>
                <td><%= pdfpage.image_file_name %></td>
                <td><%= pdfpage.image_file_size %></td>
                <td><%= pdfpage.image_updated_at.getlocal.strftime("%Y-%m-%d ") %></td>
                <td><%= link_to 'Просмотр', pdfpage %></td>
                <td><%= link_to 'Изменить', edit_pdfpage_path(pdfpage) %></td>
                <td><%= link_to 'Удалить', pdfpage, confirm: 'Уверены?', method: :delete %></td>
            </tr>
            <% end %>
        <% end %>
    </table>
    <br />

    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
<% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %> 
</div> <!-- PDF_editor -->

app/views/pdfpages/new.html.erb
<div class = "editor">
  <% if editor_signed_in? %>
    <h1>Добавление PDF-полосы</h1>
	<%= render 'form' %>
	<%= link_to 'Список', pdfpages_path %>
  <% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
  <% end %>	
</div>

app/views/pdfpages/show.html.erb
<div class = "editor">
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>

  <%= link_to 'Редактировать', edit_pdfpage_path(@pdfpage) %> |
  <%= link_to 'Список', pdfpages_path %>

  <p> <b>Издание:</b> <%= @pdfpage.edition %> </p>

  <p> <b>Дата выпуска:</b> <%= @pdfpage.pdf_date %> </p>

  <p> <b>Номер выпуска NNN:</b> <%= @pdfpage.pdf_n %> </p>

  <p> <b>Номер выпуска NNNNN:</b> <%= @pdfpage.pdf_nn %> </p>

  <p> <b>№стр.:</b> <%= @pdfpage.page_n %> </p>

  <p> <b>PDF-файл:</b> <%= @pdfpage.image_file_name %> </p>

  <p> <b>Размер:</b> <%= @pdfpage.image_file_size %> </p>

  <p> <b>Дата изм.:</b> <%= @pdfpage.image_updated_at.getlocal %> </p>

  <%= link_to 'Редактировать', edit_pdfpage_path(@pdfpage) %> |
  <%= link_to 'Список', pdfpages_path %>
</div>

app/views/pdfpages/tdpdf.html.erb
<div class = "editor">

<h1>PDF-файлы "ЩОТИЖНЯ"</h1>
  
    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
    <table>
        <tr style = "padding:2px;">
            <th>.........Издание.........</th>
            <th>.....Дата.....</th>
            <th>...NNN...</th>
            <th>...NNNNN....</th>
            <th>Cтр.</th>
            <th>Ссылка</th>
        </tr>

       <% if @pdfpages.empty? %> 
        <div> PDF-файлы отсутствуют. </div>
        <% else %>         

             <% @pdfpages.each do |pdfpage| %>
             <tr>
                <td><%= pdfpage.edition %></td>
                <td><%= pdfpage.pdf_date %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_n %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_nn %></td>
                <td style="text-align:center;"><%= pdfpage.page_n %></td>
               <!-- <td><%# link_to pdfpage.image.url, pdfpage.image.url %></td> -->
                <td><%= link_to pdfpage.image_file_name, pdfpage.image.url %></td>
            </tr>
            <% end %>
        <% end %>
    </table>
    <br />

    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
</div> <!-- PDF_editor -->

app/views/pdfpages/uppdf.html.erb
<div class = "editor">

<h1>PDF-файлы "ЮЖНАЯ ПРАВДА"</h1>
  
    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
    <table>
        <tr style = "padding:2px;">
            <th>.........Издание.........</th>
            <th>.....Дата.....</th>
            <th>...NNN...</th>
            <th>...NNNNN....</th>
            <th>Cтр.</th>
            <th>Ссылка</th>
        </tr>

       <% if @pdfpages.empty? %> 
        <div> PDF-файлы отсутствуют. </div>
        <% else %>         

             <% @pdfpages.each do |pdfpage| %>
             <tr>
                <td><%= pdfpage.edition %></td>
                <td><%= pdfpage.pdf_date %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_n %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_nn %></td>
                <td style="text-align:center;"><%= pdfpage.page_n %></td>
                <!-- <td><%# link_to pdfpage.image.url, pdfpage.image.url %></td> -->
                <td><%= link_to pdfpage.image_file_name, pdfpage.image.url %></td>
            </tr>
            <% end %>
        <% end %>
    </table>
    <br />

    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
</div> <!-- PDF_editor -->

app/views/pdfpages/vppdf.html.erb
<div class = "editor">

<h1>PDF-файлы "ВЕСТНИК ПРИБУЖЬЯ"</h1>
  
    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
    <table>
        <tr style = "padding:2px;">
            <th>.........Издание.........</th>
            <th>.....Дата.....</th>
            <th>...NNN...</th>
            <th>...NNNNN....</th>
            <th>Cтр.</th>
            <th>Ссылка</th>
        </tr>

       <% if @pdfpages.empty? %> 
        <div> PDF-файлы отсутствуют. </div>
        <% else %>         

             <% @pdfpages.each do |pdfpage| %>
             <tr>
                <td><%= pdfpage.edition %></td>
                <td><%= pdfpage.pdf_date %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_n %></td>
                <td style="text-align:center;"><%= pdfpage.pdf_nn %></td>
                <td style="text-align:center;"><%= pdfpage.page_n %></td>
                <!-- <td><%# link_to pdfpage.image.url, pdfpage.image.url %></td> -->
                <td><%= link_to pdfpage.image_file_name, pdfpage.image.url %></td>
            </tr>
            <% end %>
        <% end %>
    </table>
    <br />

    <div class = "digg_pagination"><%= will_paginate @pdfpages %></div>
</div> <!-- PDF_editor -->