config/routes.rb
Upnews::Application.routes.draw do

  devise_for :admins
  devise_for :editors

  resources :articles
  resources :infografics
  resources :pdfpages
  resources :reclams  

  get "mainpage/index" 
  

  root :to => 'mainpage#index', :as => 'mainpage'

  match '/articles' => 'articles#index'

  match '/pdfpages' => 'pdfpages#index'

  match '/uppdf1' => 'pdfpages#uppdf', as: 'uppdf'
  match '/vppdf' => 'pdfpages#vppdf', as: 'vppdf'
  match '/tdpdf' => 'pdfpages#tdpdf', as: 'tdpdf'

  match '/reclams' => 'reclams#index'

  match '/infografics' => 'infografics#index'  

  match '/articles_search' => 'articles#search',  as: 'search'  

  match '/devise' => 'devise#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/infografic.rb
# -*- encoding : utf-8 -*-
class Infografic < ActiveRecord::Base
  attr_accessible :comment, :history_date, :image, :rubric

  has_attached_file :image,
      	  :path => ":rails_root/public/assets/:class/:attachment/:id_partition/:style/:filename",
          :url => "/assets/:class/:attachment/:id_partition/:style/:filename"
          #:path => ":rails_root/system/:class/:attachment/:id_partition/:style/:filename",
          #:url => "/system/:class/:attachment/:id_partition/:style/:filename"
      #:path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      #:url => "/system/:attachment/:id/:style/:filename"
end

app/controllers/infografics_controller.rb
# -*- encoding : utf-8 -*-
class InfograficsController < ApplicationController
  
  # before_filter :authenticate

  # GET /infografics
  # GET /infografics.json
  def index
    @infografics = Infografic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infografics }
    end
  end

  # GET /infografics/1
  # GET /infografics/1.json
  def show
    @infografic = Infografic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @infografic }
    end
  end

  # GET /infografics/new
  # GET /infografics/new.json
  def new
    @infografic = Infografic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @infografic }
    end
  end

  # GET /infografics/1/edit
  def edit
    @infografic = Infografic.find(params[:id])
  end

  # POST /infografics
  # POST /infografics.json
  def create
    @infografic = Infografic.new(params[:infografic])

    respond_to do |format|
      if @infografic.save
        format.html { redirect_to @infografic, notice: 'Блок инфографики успешно создан.' }
        format.json { render json: @infografic, status: :created, location: @infografic }
      else
        format.html { render action: "new", layout: "infografics" }
        format.json { render json: @infografic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infografics/1
  # PUT /infografics/1.json
  def update
    @infografic = Infografic.find(params[:id])

    respond_to do |format|
      if @infografic.update_attributes(params[:infografic])
        format.html { redirect_to @infografic, notice: 'Блок инфографики успешно обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @infografic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infografics/1
  # DELETE /infografics/1.json
  def destroy
    @infografic = Infografic.find(params[:id])
    @infografic.destroy

    respond_to do |format|
      format.html { redirect_to infografics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/infografics_helper.rb
module InfograficsHelper
end

app/views/infografics/_form.html.erb
  <%= form_for(@infografic) do |f| %>
  <% if @infografic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@infografic.errors.count, "error") %> prohibited this infografic from being saved:</h2>

    <ul>
      <% @infografic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<h4>Редактирование ИНФОГРАФИКИ . . . .Редактор: <%# current_editor.email  %> </h4>
  <fieldset>   
    <div id="new_article_input"> <!-- start.input block-->
   <div style="float:left;">
      <div class="field">
        <%= f.label "*Рубрика" %><br />
        <%# f.text_field :rubric, required: "true" %>
        <%= select(:infografic, :rubric, options_for_select([['День в истории', 'День в истории'], ['Прочие', 'Прочие']], @infografic.rubric || 'День в истории')) %>
      </div>
      
      <br />
      <div class="field">
        <%= f.label "Комментарий" %><br />
        <%= f.text_field :comment %>
      </div>
      
      <br />
      <div class="field">
        <%= f.label "Дата (ОБЯЗАТЕЛЬНО для рубрики `День в истории`, год - любой)" %><br />
        <%= f.date_select :history_date %>
      </div>
</div> 
<div style="float:right;">
      <div class="field" id="inp_image">
        <%= f.label "*графический файл" %><br />
        <%= f.file_field :image %>
        <% if @infografic.image? %>
        <%# image_tag(@infografic.image.url, size: "180x360", :border=>0) %>
        <br />
        <a href="<%= @infografic.image.url %>"> <%= image_tag(@infografic.image.url, size: "180x360", :border=>0) %> </a>
        <%= @infografic.image_file_name  %>
        <% end %>
      </div>
    </div> <!-- end. new_article_input-->
</div>    
    <div class="actions" style="clear:both; float:right;">
      <%= f.submit "Сохранить" %>
    </div>
    
  </fieldset>
  <% end %>

app/views/infografics/edit.html.erb
<div class = "editor">
<% if editor_signed_in? %>
	<%= render 'form' %>
	<%= link_to 'Показать', @infografic %> |
	<%= link_to 'Список', infografics_path %>
<% else %>
        <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %>	
</div>

app/views/infografics/index.html.erb
<div class = "editor">
<% if editor_signed_in? %>
  <h4>Перечень ИНФОГРАФИКИ <%#= current_editor.email %> </h4>
  <nav class="action">
    <%= link_to 'ДОБАВИТЬ БЛОК ИНФОГРАФИКИ', new_infografic_path %>
  </nav>
      <br />
      <table>
        <tr>
          <th>Рубрика</th>
          <th>Комментарий</th>
          <th>"Дата в истории"</th>
          <th>Файл</th>
          <th>Тип файла</th>
          <th>Размер</th>
          <th>Дата обновления</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      
      <% @infografics.each do |infografic| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td><%= infografic.rubric %></td>
          <td><%= infografic.comment %></td>
          <td><%= infografic.history_date %></td>
          <td><%= infografic.image_file_name %></td>
          <td><%= infografic.image_content_type %></td>
          <td><%= infografic.image_file_size %></td>
          <td><%= infografic.updated_at.getlocal.strftime("%Y-%m-%d ") %></td >
          <td><%= link_to 'Показать', infografic %></td>
          <td><%= link_to 'Изменить', edit_infografic_path(infografic) %></td>
          <td><%= link_to 'Удалить', infografic, confirm: 'Уверены?', method: :delete %></td>
        </tr>
      <% end %>
      </table>
        
    <br />
<% else %>
    <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %> 
</div> <!-- infografic_editor -->

app/views/infografics/new.html.erb
<div class = "editor">
<% if editor_signed_in? %>
	<h4>Новый блок ИНФОГРАФИКИ</h4>

	<%= render 'form' %>

	<%= link_to 'Список', infografics_path %>
<% else %>
    <h3 style = "text-align: center; color: #FF0000;"> Перейдите в режим "Админ".  </h3 >
<% end %>
</div>

app/views/infografics/show.html.erb
<div class = "editor">
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>

<div style= "float:left; width:470px; padding-left:30px; ">

   <% if @infografic.image? %>
      <%= image_tag(@infografic.image.url, size: "200x500", :border=>0) %>
   <% end %>
</div>

<div style= "float:right; width:470px; ">
<%# link_to @infografic.image.url, @infografic.image.url  %>
<%= @infografic.image_file_name  %>
<p>
  <b>Рубрика:</b>
  <%= @infografic.rubric %>
</p>

<p>
  <b>Комментарий:</b>
  <%= @infografic.comment %>
</p>

<p>
  <b>Дата (рубрика "День в истории"):</b>
  <%= @infografic.history_date %>
</p>

<p>
  <b>Имя файла:</b>
  <%= @infografic.image_file_name %>
</p>

<p>
  <b>Тип файла:</b>
  <%= @infografic.image_content_type %>
</p>

<p>
  <b>Размер файла:</b>
  <%= @infografic.image_file_size %>
</p>

<p>
  <b>Дата обновления изображения:</b>
  <%= @infografic.image_updated_at %>
</p>
</div>

<div style = "clear:both; float:right; padding-right:20px;">
  <%= link_to 'Редактировать', edit_infografic_path(@infografic) %> |
  <%= link_to 'Список', infografics_path %>
</div>
</div>